choco install -y googlechrome
choco install -y putty.install
choco install -y openvpn
choco install -y 7zip.install
choco install -y git
choco install -y git.install
choco install -y namebench
choco install -y sublimetext3
choco install -y mpv.install