choco install -y 7zip.install
choco install -y discord
choco install -y filezilla
choco install -y firefox
choco install -y github-desktop
choco install -y hwmonitor
choco install -y itunes
choco install -y k-litecodecpackfull 
#choco install -y microsoft-windows-terminal #not working with fresh 1903 atm
choco install -y mpv
choco install -y putty
choco install -y mremoteng
choco install -y nextcloud-client
choco install -y namebench
choco install -y powertoys
choco install -y signal
choco install -y steam
choco install -y sublimetext3
choco install -y lenovo-thinkvantage-system-update