choco install -y 7zip.install
choco install -y discord
choco install -y filezilla
choco install -y firefox
choco install -y github-desktop
choco install -y googlechrome
choco install -y hwmonitor
choco install -y k-litecodecpackfull 
choco install -y mpv 
choco install -y putty
choco install -y mremoteng 
choco install -y namebench
choco install -y openvpn
choco install -y signal
choco install -y slack
choco install -y steam
choco install -y spotify
choco install -y sublimetext3
choco install -y vmwareworkstation
choco install -y office365proplus