choco install -y 7zip
choco install -y discord
choco install -y rufus
choco install -y filezilla
choco install -y firefox
choco install -y geforce-game-ready-driver
choco install -y github-desktop
choco install -y hwmonitor
choco install -y k-litecodecpackfull
choco install -y microsoft-windows-terminal
choco install -y putty
choco install -y namebench
choco install -y powertoys
choco install -y signal
choco install -y steam
choco install -y epicgameslauncher
choco install -y sublimetext4
choco install -y streamdeck
choco install -y winrar
choco install -y cpu-z 
choco install -y crystaldiskinfo
choco install -y deluge
choco install -y libreoffice-fresh
choco install -y markdown-edit
choco install -y nordvpn
choco install -y obs-studio
choco install -y spotify
choco install -y teamviewer
choco install -y telegram
choco install -y tor-browser
choco install -y virtualbox
choco install -y vlc
choco install -y wireguard